set(_CATKIN_CURRENT_PACKAGE "odometry_setup")
set(odometry_setup_VERSION "0.0.0")
set(odometry_setup_MAINTAINER "kg <kg@todo.todo>")
set(odometry_setup_PACKAGE_FORMAT "2")
set(odometry_setup_BUILD_DEPENDS "roscpp" "tf")
set(odometry_setup_BUILD_EXPORT_DEPENDS "roscpp" "tf")
set(odometry_setup_BUILDTOOL_DEPENDS "catkin")
set(odometry_setup_BUILDTOOL_EXPORT_DEPENDS )
set(odometry_setup_EXEC_DEPENDS "roscpp" "tf")
set(odometry_setup_RUN_DEPENDS "roscpp" "tf")
set(odometry_setup_TEST_DEPENDS )
set(odometry_setup_DOC_DEPENDS )
set(odometry_setup_URL_WEBSITE "")
set(odometry_setup_URL_BUGTRACKER "")
set(odometry_setup_URL_REPOSITORY "")
set(odometry_setup_DEPRECATED "")