set(_CATKIN_CURRENT_PACKAGE "motor_setup")
set(motor_setup_VERSION "0.0.0")
set(motor_setup_MAINTAINER "kg <kg@todo.todo>")
set(motor_setup_PACKAGE_FORMAT "2")
set(motor_setup_BUILD_DEPENDS "rospy")
set(motor_setup_BUILD_EXPORT_DEPENDS "rospy")
set(motor_setup_BUILDTOOL_DEPENDS "catkin")
set(motor_setup_BUILDTOOL_EXPORT_DEPENDS )
set(motor_setup_EXEC_DEPENDS "rospy")
set(motor_setup_RUN_DEPENDS "rospy")
set(motor_setup_TEST_DEPENDS )
set(motor_setup_DOC_DEPENDS )
set(motor_setup_URL_WEBSITE "")
set(motor_setup_URL_BUGTRACKER "")
set(motor_setup_URL_REPOSITORY "")
set(motor_setup_DEPRECATED "")